#!/usr/bin/env python3
"""Build the third-draft configuration table from approved protocol records."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
INPUT = ROOT / "evidence_overrides" / "author_verified_protocol.csv"
OUTPUT = ROOT / "tables" / "generated" / "tab01_configuration.tex"
SUPPLEMENT_OUTPUT = ROOT / "tables" / "generated" / "tabS01_full_configuration.tex"

FULL_DISPLAY_KEYS = (
    "domain",
    "covariance",
    "likelihood",
    "principal_lengthscale",
    "mask",
    "seeds",
    "nuts_chains",
    "nuts_warmup",
    "nuts_retained",
    "architecture",
    "embedding",
    "hidden",
    "train_steps",
    "batch_size",
    "validation",
    "optimiser",
    "decoder_seed",
)

MAIN_ROWS = (
    ("Domain", ("domain",)),
    ("Latent field", ("covariance", "principal_lengthscale")),
    ("Likelihood", ("likelihood",)),
    ("Observation protocol", ("mask",)),
    ("Dataset seeds", ("seeds",)),
    ("NUTS per chain", ("nuts_chains", "nuts_warmup", "nuts_retained")),
    ("Decoder", ("architecture", "embedding", "hidden")),
    (
        "Optimisation",
        ("train_steps", "batch_size", "validation", "optimiser", "decoder_seed"),
    ),
)


def latex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in value)


def main() -> None:
    with INPUT.open(newline="", encoding="utf-8") as handle:
        records = {row["key"]: row for row in csv.DictReader(handle)}
    missing = [key for key in FULL_DISPLAY_KEYS if key not in records]
    if missing:
        raise RuntimeError(f"Missing approved configuration records: {missing}")

    full_rows = []
    for key in FULL_DISPLAY_KEYS:
        record = records[key]
        scope = (
            "all reported grids"
            if record["scope"] == "all_reported"
            else r"$32\times32$ and $64\times64$"
        )
        full_rows.append(
            f"{latex_escape(record['display_label'])} & "
            f"{latex_escape(record['value'])} & {scope} \\\\"  # two LaTeX slashes
        )

    main_rows = []
    for label, keys in MAIN_ROWS:
        values = "; ".join(records[key]["value"] for key in keys)
        scopes = {records[key]["scope"] for key in keys}
        if len(scopes) != 1:
            raise RuntimeError(f"Mixed scopes in main-table row {label}: {scopes}")
        scope = (
            "all reported grids"
            if scopes == {"all_reported"}
            else r"$32\times32$ and $64\times64$"
        )
        main_rows.append(
            f"{latex_escape(label)} & {latex_escape(values)} & {scope} \\\\"
        )

    content = "\n".join(
        [
            "% Generated by scripts/tables/build_configuration_table.py",
            "% Source: evidence_overrides/author_verified_protocol.csv",
            r"\begin{tabular}{>{\raggedright\arraybackslash}p{0.28\textwidth} >{\raggedright\arraybackslash}p{0.39\textwidth} >{\raggedright\arraybackslash}p{0.20\textwidth}}",
            r"\toprule",
            r"Setting & Retained value & Scope \\",
            r"\midrule",
            *main_rows,
            r"\bottomrule",
            r"\end{tabular}",
            "",
        ]
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")

    supplement_content = "\n".join(
        [
            "% Generated by scripts/tables/build_configuration_table.py",
            "% Source: evidence_overrides/author_verified_protocol.csv",
            r"\begin{longtable}{>{\raggedright\arraybackslash}p{0.28\textwidth} >{\raggedright\arraybackslash}p{0.39\textwidth} >{\raggedright\arraybackslash}p{0.20\textwidth}}",
            r"\caption{Complete retained experimental configuration.}\label{tab:supp-full-configuration}\\",
            r"\toprule",
            r"Setting & Retained value & Scope \\",
            r"\midrule",
            r"\endfirsthead",
            r"\toprule",
            r"Setting & Retained value & Scope \\",
            r"\midrule",
            r"\endhead",
            *full_rows,
            r"\bottomrule",
            r"\end{longtable}",
            "",
        ]
    )
    SUPPLEMENT_OUTPUT.write_text(supplement_content, encoding="utf-8")


if __name__ == "__main__":
    main()
